services:

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    restart: always

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    restart: always