services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    # env_file: .env
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    # env_file: .env
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass