# Generated by Django 3.2.16 on 2024-04-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20240410_1641'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscription',
        ),
    ]
